// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_fashion
Rcpp::CharacterVector rcpp_fashion(Rcpp::CharacterVector x, std::string pattern, char replace_char);
RcppExport SEXP _barah_rcpp_fashion(SEXP xSEXP, SEXP patternSEXP, SEXP replace_charSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< char >::type replace_char(replace_charSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fashion(x, pattern, replace_char));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_barah_rcpp_fashion", (DL_FUNC) &_barah_rcpp_fashion, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_barah(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
