# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_fashion <- function(x, pattern, replace_char) {
    .Call(`_barah_rcpp_fashion`, x, pattern, replace_char)
}

